### ISSUE TITLE
contacts with the speakers 

### ISSUE THREAD

**Issue by gorhgorh** [squatconf/talks#18]
@kalikaneko, holger krekel @layerzerolabs @elf-pavlik and all that did not already responded to my mail, can you please ping me so I can work on your accommodations. 

drop me a mail here or shoot at gorhgorh at lesnodebots.eu

thanks and see you soon in Paris :)

**Comment by dignifiedquire** [comment]
Closing this to avoid any confusion with the upcoming conf.
