### ISSUE TITLE
I propose we rename this to `talks-2016`

### ISSUE THREAD

**Issue by ralphtheninja** [squatconf/talks#27]

**Comment by cjdelisle** [comment]
I already dropped the link to people so if we change it, they're going to end up on a 404

**Comment by gorhgorh** [comment]
I kept 2015 things on a separate branch, and since Caleb already croped the url let's leave it htis way yep

**Comment by ralphtheninja** [comment]
> I already dropped the link to people so if we change it, they're going to end up on a 404

They wouldn't, since github redirects, but it's fine.
